# Generated by Django 3.0.4 on 2020-04-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0003_ost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ost',
            name='artists',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='vgmdb_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
