# Generated by Django 3.0.4 on 2020-04-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0005_auto_20200408_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2555)),
            ],
        ),
        migrations.RemoveField(
            model_name='ost',
            name='artists',
        ),
        migrations.AddField(
            model_name='ost',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, to='ost.Artists'),
        ),
    ]
