# Generated by Django 3.0.4 on 2020-04-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0006_auto_20200408_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ost',
            name='cover',
            field=models.ImageField(blank=True, default='default.png', upload_to='covers/%Y/%m/%D/'),
        ),
    ]
