# Generated by Django 3.0.4 on 2020-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0009_auto_20200410_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='location',
        ),
        migrations.AddField(
            model_name='animation',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/title/'),
        ),
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/title/'),
        ),
        migrations.AddField(
            model_name='platform',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/title/'),
        ),
        migrations.AddField(
            model_name='serie',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/title/'),
        ),
        migrations.AlterField(
            model_name='ost',
            name='artists',
            field=models.ManyToManyField(blank=True, to='ost.Artists'),
        ),
        migrations.AlterField(
            model_name='ost',
            name='publisher_or',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ost',
            name='type',
            field=models.ManyToManyField(to='ost.Type'),
        ),
    ]
