# Generated by Django 3.0.4 on 2020-04-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0010_auto_20200410_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ost',
            name='platform_or',
        ),
    ]
