# Generated by Django 3.0.4 on 2020-04-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0011_remove_ost_platform_or'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ost',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='ost',
            name='publisher_or',
        ),
        migrations.AddField(
            model_name='ost',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
