# Generated by Django 3.0.4 on 2020-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0012_auto_20200419_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ost',
            old_name='products_or',
            new_name='animation_or',
        ),
        migrations.RemoveField(
            model_name='ost',
            name='products',
        ),
        migrations.RemoveField(
            model_name='ost',
            name='animation',
        ),
        migrations.AddField(
            model_name='ost',
            name='animation',
            field=models.ManyToManyField(blank=True, null=True, to='ost.Animation'),
        ),
        migrations.RemoveField(
            model_name='ost',
            name='games',
        ),
        migrations.AddField(
            model_name='ost',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, to='ost.Game'),
        ),
        migrations.RemoveField(
            model_name='ost',
            name='platform',
        ),
        migrations.AddField(
            model_name='ost',
            name='platform',
            field=models.ManyToManyField(blank=True, null=True, to='ost.Platform'),
        ),
    ]
