# Generated by Django 3.0.4 on 2020-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0014_auto_20200419_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ost',
            old_name='game',
            new_name='class_game',
        ),
        migrations.AddField(
            model_name='ost',
            name='class_animation',
            field=models.BooleanField(default=False),
        ),
    ]
