# Generated by Django 3.0.4 on 2020-04-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0015_auto_20200419_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ost',
            old_name='body',
            new_name='tracklist',
        ),
        migrations.RemoveField(
            model_name='ost',
            name='animation_or',
        ),
        migrations.RemoveField(
            model_name='ost',
            name='games_or',
        ),
        migrations.AddField(
            model_name='ost',
            name='other_animation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='other_games',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ost',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
