# Generated by Django 3.0.4 on 2020-04-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0016_auto_20200420_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
