# Generated by Django 3.0.4 on 2020-04-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0017_auto_20200421_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ost',
            name='artists_or',
        ),
        migrations.AddField(
            model_name='animation',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='ost',
            name='artists',
        ),
        migrations.AddField(
            model_name='ost',
            name='artists',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ost',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Artists',
        ),
    ]
