# Generated by Django 3.0.4 on 2020-04-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0018_auto_20200421_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='ost',
            name='amazon_hmtl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
