# Generated by Django 3.0.4 on 2020-04-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0019_ost_amazon_hmtl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ost',
            old_name='amazon_hmtl',
            new_name='amazon_html',
        ),
    ]
