# Generated by Django 3.0.4 on 2020-04-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0020_auto_20200422_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='ost',
            name='amazon_jp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='amazon_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='cd_japan_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='google_play',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='itunes',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='mora',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='other_link_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='other_link_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='other_link_site_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='other_link_site_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='ototoy',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='play_asia_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='spotify_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='steam',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ost',
            name='amazon_html',
            field=models.URLField(blank=True, null=True),
        ),
    ]
