# Generated by Django 3.0.4 on 2020-04-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0023_auto_20200424_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='ost',
            name='download_link_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='download_link_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='download_link_choices_2',
            field=models.CharField(choices=[('MG', 'MEGA'), ('MF', 'MediaFire'), ('GD', 'Google Drive'), ('BD', 'BeDrive'), ('MI', 'Mirror')], default='MG', max_length=2),
        ),
        migrations.AddField(
            model_name='ost',
            name='download_link_choices_3',
            field=models.CharField(choices=[('MG', 'MEGA'), ('MF', 'MediaFire'), ('GD', 'Google Drive'), ('BD', 'BeDrive'), ('MI', 'Mirror')], default='GD', max_length=2),
        ),
        migrations.AlterField(
            model_name='ost',
            name='download_link_choices_1',
            field=models.CharField(choices=[('MG', 'MEGA'), ('MF', 'MediaFire'), ('GD', 'Google Drive'), ('BD', 'BeDrive'), ('MI', 'Mirror')], default='MF', max_length=2),
        ),
    ]
