# Generated by Django 3.0.4 on 2020-04-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0026_auto_20200424_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='ost',
            name='download_link_1_flac',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='download_link_1_soc_flac',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='download_link_2_flac',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='download_link_2_soc_flac',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='download_link_3_flac',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='download_link_3_soc_flac',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ost',
            name='download_link_choices_1_flac',
            field=models.CharField(choices=[('MEGA', 'MEGA'), ('MediaFire', 'MediaFire'), ('Google Drive', 'Google Drive'), ('BeDrive', 'BeDrive'), ('Mirror', 'Mirror')], default='MediaFire', max_length=20),
        ),
        migrations.AddField(
            model_name='ost',
            name='download_link_choices_2_flac',
            field=models.CharField(choices=[('MEGA', 'MEGA'), ('MediaFire', 'MediaFire'), ('Google Drive', 'Google Drive'), ('BeDrive', 'BeDrive'), ('Mirror', 'Mirror')], default='MEGA', max_length=20),
        ),
        migrations.AddField(
            model_name='ost',
            name='download_link_choices_3_flac',
            field=models.CharField(choices=[('MEGA', 'MEGA'), ('MediaFire', 'MediaFire'), ('Google Drive', 'Google Drive'), ('BeDrive', 'BeDrive'), ('Mirror', 'Mirror')], default='Google Drive', max_length=20),
        ),
    ]
