# Generated by Django 3.0.4 on 2020-04-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0027_auto_20200425_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='ost',
            name='releated_ost',
            field=models.ManyToManyField(blank=True, to='ost.Ost'),
        ),
    ]
